blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/desksh/desk-cli/wiki
    about: Check our documentation for usage guides and FAQ
  - name: Discussions
    url: https://github.com/desksh/desk-cli/discussions
    about: Ask questions and share ideas in GitHub Discussions
